### ISSUE TITLE
False Connection on VPN

### ISSUE THREAD

**Issue by Nexow91** [XeroxDev/Loupedeck-plugin-YTMDesktop#1]
Hello, 

I'm currently using the last version of the plugin and I think it's really awesome, unfortunately there are some network problems because I use a Wireguard vpn, the loupdeck can often not connect to the ytm app. On the ytm app website I see two connections, one from the pc and one from the wireguard.

If wireguard is not open at first, I can connect to the app as normal and then open wireguard without any further problems.

But if I open wireguard beforehand, no connection can be established and the problem is if I then close Wireguard and, for example, press the like button on the loupedeck, loupedeck crashes and the plugin becomes unusable until I reinstall it again.

I tried to find the option after the readme to be able to make network settings myself to assign a fixed ip to the YTM app or the Loupedeck, unfortunately I couldn't find it.

I'm on the localhost website as directed no matter what I press I can't store IP addresses or ports as I don't see an option to enter anything I only see an IP address with a QR code and if devices are connected and secured.

- Click on the open Icon or go to http://localhost:9863/ (Default)
- Optional: Activate password protection. else go to 7.
- Add “Open settings” action and touch it
- Add all settings. (Host, Port, Password)
- Click save

--------------------------------------------------------------------------------------------

EDIT: 

I found the network settings and will adjust the settings and then report if it works.
The settings had to be assigned to a button using Loupedeck.

Loupedeck crashes once when running a VPN. YTM Plugin crashed and needs to be reactivated. After activation, all functions are available again.

On the localhost website, the IP address of the VPN connection is also displayed, not just the local ip, I think it's because it's also trying to establish a connection against the tunnel, even though I've specified the IP address.

You would have to have a way to use or display only one network adapter, then you would ignore the other connection.

--------------------------------------------------------------------------------------------

thank you in advance for the great service.

Regards

**Comment by XeroxDev** [comment]
Hello and sorry for the late response.

Thank you for opening the issue and the incredible detailed information! 

I will look into it and check how I can fix it.

**Comment by XeroxDev** [comment]
Cleanup. This got fixed a long time ago, just forgot to close it. My bad 😅

**Comment by Nexow91** [comment]
haha no problem thx for feedback :)
